// Migrate an existing static llms.txt file into agent-ready.config.json.
// This is intentionally local-only and file-based. We do not query host app tables
// because every Convex app organizes content differently and auth rules vary.
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const DEFAULT_SOURCE_CANDIDATES = ["public/llms.txt", "static/llms.txt", "llms.txt"];

// Parse a markdown llms.txt-style file into title, description, sections, and links.
// We support the common patterns: H1 title, blockquote description, H2 section headings
// followed by `- [Title](path): description` bullets. Pages that do not match are skipped
// with a warning so the user can fix them by hand.
export function parseLlmsTxt(source) {
  const lines = source.split(/\r?\n/);
  let title = "";
  let description = "";
  const pages = [];
  let currentSection = "";
  let captureDescription = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!title && /^#\s+/.test(trimmed)) {
      title = trimmed.replace(/^#\s+/, "").trim();
      captureDescription = true;
      continue;
    }

    if (captureDescription && /^>\s*/.test(trimmed)) {
      const part = trimmed.replace(/^>\s*/, "").trim();
      description = description ? `${description} ${part}` : part;
      continue;
    }

    if (/^##\s+/.test(trimmed)) {
      currentSection = trimmed.replace(/^##\s+/, "").trim();
      captureDescription = false;
      continue;
    }

    // Match `- [Title](path)` or `- [Title](path): description`.
    const bullet = trimmed.match(/^[-*]\s+\[([^\]]+)\]\(([^)]+)\)\s*(?::\s*(.*))?$/);
    if (bullet) {
      const [, pageTitle, rawHref, rawDescription] = bullet;
      let pagePath = rawHref.trim();
      // Drop the absolute URL prefix when present so the page path stays portable.
      try {
        const parsed = new URL(rawHref);
        pagePath = parsed.pathname || "/";
      } catch {
        // not absolute, leave as is
      }
      // Skip discovery files. They get generated by agent-ready.
      if (
        pagePath.endsWith("/llms.txt") ||
        pagePath.endsWith("/agents.md") ||
        pagePath.endsWith("/llms-full.txt")
      ) {
        continue;
      }
      pages.push({
        title: pageTitle.trim(),
        path: pagePath,
        description: (rawDescription ?? "").trim(),
        section: currentSection || undefined,
      });
    }
  }

  return { title, description, pages };
}

async function resolveSource(args) {
  if (args.from) {
    const explicit = path.resolve(args.from);
    if (!existsSync(explicit)) {
      throw new Error(`File not found: ${args.from}`);
    }
    return explicit;
  }
  for (const candidate of DEFAULT_SOURCE_CANDIDATES) {
    const abs = path.resolve(candidate);
    if (existsSync(abs)) return abs;
  }
  throw new Error(
    "No source file. Pass --from <path> or place llms.txt in public/, static/, or the project root.",
  );
}

export async function importCmd(args) {
  const source = await resolveSource(args);
  const raw = await readFile(source, "utf8");
  const parsed = parseLlmsTxt(raw);

  const configPath = path.resolve(args.config || "agent-ready.config.json");
  const legacy = path.resolve("llms-txt.config.json");
  let existing = {};
  if (existsSync(configPath)) {
    existing = JSON.parse(await readFile(configPath, "utf8"));
  } else if (existsSync(legacy)) {
    existing = JSON.parse(await readFile(legacy, "utf8"));
  }

  // Merge by path. If a page already exists in config, keep the existing one unless --overwrite.
  const existingPages = Array.isArray(existing.pages) ? existing.pages : [];
  const byPath = new Map(existingPages.map((p) => [p.path, p]));
  let added = 0;
  let updated = 0;
  for (const page of parsed.pages) {
    if (byPath.has(page.path)) {
      if (args.overwrite) {
        byPath.set(page.path, { ...byPath.get(page.path), ...page });
        updated++;
      }
      continue;
    }
    byPath.set(page.path, page);
    added++;
  }

  const merged = {
    ...existing,
    settings: {
      ...(existing.settings ?? {}),
      // Only set title and description when the existing config did not have them.
      // Avoid clobbering values the user already chose in the wizard.
      appName: existing.settings?.appName || parsed.title || existing.settings?.appName,
      description:
        existing.settings?.description || parsed.description || existing.settings?.description,
    },
    pages: Array.from(byPath.values()),
    endpoints: existing.endpoints ?? [],
  };

  if (args["dry-run"]) {
    console.log(`Parsed ${parsed.pages.length} pages from ${path.relative(process.cwd(), source)}`);
    console.log(`Would add ${added} pages, update ${updated} pages.`);
    if (parsed.title) console.log(`Title: ${parsed.title}`);
    if (parsed.description) console.log(`Description: ${parsed.description}`);
    return;
  }

  await writeFile(configPath, JSON.stringify(merged, null, 2) + "\n");
  console.log("");
  console.log(`Imported ${parsed.pages.length} pages from ${path.relative(process.cwd(), source)}`);
  console.log(`  Added: ${added}`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Wrote: ${path.relative(process.cwd(), configPath)}`);
  console.log("");
  console.log("Next: run `npx agent-ready sync` to push the config to your deployment.");
}
